### ISSUE TITLE
Use v3 for catalog API

### ISSUE THREAD

**Issue by rfink** [getconversio/node-bigcommerce#19]
Catalog API is now at V3, which is backwards compatible, but enables new features. Addressed by #18.

**Comment by dlebech** [comment]
@rfink Thanks for reporting this. Your PR #18 is now published as version 2.1.0 on npm :smiley: 

Let me know if there is anything else related to this that needs to be done. Thanks again!

**Comment by rfink** [comment]
No, thank you!
