### ISSUE TITLE
Install node-bigcommerce error

### ISSUE THREAD

**Issue by ocvninfo** [getconversio/node-bigcommerce#32]
I installed **node-bigcommerce**.
But node-bigcommerce is not working when i run **stencil start** . 
![image](https://user-images.githubusercontent.com/3072481/27165392-c9a5253c-51bd-11e7-90c6-fa37f2a34a56.png)
Is there any way to fix this?
Thanks

**Comment by dlebech** [comment]
This does seem to be related to node-bigcommerce but rather looks like a loader problem with webpack when trying to parse the package json file. I.e. it's related to either stencil itself or the setup of it.

**Comment by dlebech** [comment]
I'm closing this issue now, since we haven't heard anything back, and it's not an error in the library.
