### ISSUE TITLE
SPA front end app question

### ISSUE THREAD

**Issue by walshe** [getconversio/node-bigcommerce#42]
I am implementing a a Big Commerce (BC) app which will be a single page app created from React.js.  There will be no backend/node.js server but rather multiple serverless api gateway endpoints that will be called from the react.js app.

correct me if I am wrong on the way things should work in terms of authentiation with my app:

1. User logs into BC, installs and then launches my app
2. my app will receive an oauth token from BC and store it in session storage
3. for each request that my app makes to my serverless functions it should pass along the oauth token and on the server side the node-bigcommerce module should be used to verify this oauth token.
4 A valid token allows login to my app otherwise acccess is denied

**Comment by stefanosala** [comment]
Hi @walshe, very sorry, but this module doesn't work in a browser's context.

**Comment by walshe** [comment]
yes , I edited my original question.. now I think I got it right above
