### ISSUE TITLE
Simple question around auth..

### ISSUE THREAD

**Issue by walshe** [getconversio/node-bigcommerce#44]
Hi, looking for some advice..

So I have created an app for BigCommerce. In the BigCommerce app I have the auth callback configured so that it calls my backend 

`
        export async function oauth(event, context, callback) {

    bigCommerce.authorize(JSON.stringify(event.queryStringParameters))
        .then(data => {

            console.log('Authorized! ' + JSON.stringify(data));

            callback(null, {
                statusCode: 302,
                headers: {
                    Location: '<some path in my app>',
                },
            })

        }).catch(error => {
            callback(null, failure(error));

        });

    }

`

when I authorize I get something like  the following back fro bigcommerce {"context":"stores/xxxx","code":"gpkof3rxxxxxxxwqjkv77dffq7w","scope":"store_v2_default"}

So I assume I do something like this:

- I save this store and code somewhere in the backend - i.e. in session .. or db in my case as I am using a stateless auth pattern with a react single page app. 
- I send the code 'gpkof3rxxxxxxxwqjkv77dffq7w' back to the frontend (probably encrypted) where it is stored safely in a the browser session or cookie.
- The code is sent in all subsequent requests (in the header) and used to identify the user making the requests

have I got this correct ? thanks

**Comment by stefanosala** [comment]
You got it correctly 👍
