### ISSUE TITLE
Cant get token bigCommerce.authorize

### ISSUE THREAD

**Issue by ohabash** [getconversio/node-bigcommerce#48]
I dont have a problem to report. I just need help. 

The following is what my app looks like now. 

```
const BigCommerce = require('node-bigcommerce');

const bigCommerce = new BigCommerce({
    logLevel: 'info',
    clientId: 'from app creation',
    secret: 'from app creation',
    callback: 'http://localhost:3200/auth',
    responseType: 'json',
    apiVersion: 'v3',
    accessToken: 'from an api account created in bc store admin',
    storeHash: 'ziq4j28bpo'
});


router.get("/auth", (req, res, next) => {
    bigCommerce
        .authorize(req.query)
        .then(data => res.render("auth", { title: "Authorized!", data: data }))
        .catch(next);
});
```

What can I do now to get the token? I am trying `GET http://localhost:3200/api/auth` but that returns a message "you are being redirected to"... It must be obvious to most but I cant figure out how to use the authorize function. Please Help!

**Comment by bdodroid** [comment]
Did you ever figure this out? I'm also stuck with "you are being redirected to".......

**Comment by stefanosala** [comment]
@ohabash @bdodroid you don't need `apiVersion`, `accessToken` and `storeHash` when you call `authorize` :)

**Comment by bdodroid** [comment]
Ok, here's my setup
```
const BigCommerceAuth = require('node-bigcommerce');

const bigCommerce2 = new BigCommerceAuth({
    clientId: '<cleintidhere>',
    secret: '<secretcodehere>',
    callback: 'http://localhost:3030/bigcommerce/auth',
    responseType: 'json'
});

router.get('/auth', (req, res, next) => {
    bigCommerce2.authorize(req.query)
    .then(data => res.render('bc_auth', { title: 'Authorized!', data: data }))
    .catch(next);
});

router.get('/prod', (req, res, next) => {
    bigCommerce2.get('/products')
        .then(data => {
            console.log(data);
        // Catch any errors, or handle the data returned
    });
});
```
Unfortunately I am still seeing "you are being redirected" when hitting /auth, am I missing something?

**Comment by ohabash** [comment]
@stefanosala does having the extra data have something to do with the error? I get the sense there is no problem just lack of literature

**Comment by ohabash** [comment]
@stefanosala Can you show me an example request to this function?
