### ISSUE TITLE
Does this module help get the customers token

### ISSUE THREAD

**Issue by ohabash** [getconversio/node-bigcommerce#52]
In my app my customers will need to login  as if they were on the bc store. I am able to verify that the provided email and password are correct. I cant find a method to exchange the user_id and my app credentials for a token that can be used in sso ([described here](https://developer.bigcommerce.com/api/v2/#customer-login-api))

I used the[ python sdk](https://github.com/bigcommerce/bigcommerce-api-python) before and the part I want to do now in nodejs is the following

```
bc_client = b.api.BigcommerceApi(client_id, store_hash, access_token)
login_token = sdk.customer_login_token.create(bc_client, customer.id)
```

**Comment by stefanosala** [comment]
Feel free to post another comment if you need more help.
