### ISSUE TITLE
Get request error: the access token and store hash are required to call the BigCommerce API

### ISSUE THREAD

**Issue by flashsnake-so** [getconversio/node-bigcommerce#53]
I just tried to use the example for /products get products api. However, it doesn't work without the store hash. I am working on server-to-server call. I don't know what needs to be done.

```
Get request error: the access token and store hash are required to call the BigCommerce API
```

**Comment by PeteyRev** [comment]
@flashsnake-so You need to get the store hash, you see that when you get the API credentials

**Comment by flashsnake-so** [comment]
Thanks. I contacted the customer support months ago and got that resolved. The link is helpful as well.
