### ISSUE TITLE
4xx/5xx response body gets swallowed

### ISSUE THREAD

**Issue by chrisEff** [getconversio/node-bigcommerce#61]
If the API responds with a 4xx or 5xx code, it's next to impossible to get the response body, because it's swallowed here:
https://github.com/getconversio/node-bigcommerce/blob/1ac28d8f2e374cf4c14e3be65be80b28aba90b0a/lib/request.js#L112

The only way would be to parse it from the Error's message, which would be very ugly.

**Comment by chrisEff** [comment]
Hey guys,
if someone could have a quick look at my pull request, that would be much appreciated!
Cheers!

**Comment by jmnsf** [comment]
Closed by #62
