### ISSUE TITLE
Error response are gibberish \u001f\b\u0000\u0000\u0000\u0000\u0000\u0000\u00004»\u000eÂ0\fEÅ\nk\u001fRÅÔ\u001f\bi-µq°ÝJ¨ê¿\n\u0018,ÝáÜ{¼95oºþÜu3²\t]ïn¤Ji\u0000\u0016 \u0014X\

### ISSUE THREAD

**Issue by ohabash** [getconversio/node-bigcommerce#66]
Do you no why my error responses from BigCommerce are not readable?

>"error": "Error: Request returned error code: 422 and body: \u001f\b\u0000\u0000\u0000\u0000\u0000\u0000\u00004»\u000eÂ0\fEÅ\nk\u001fRÅÔ\u001f\bi-µq°ÝJ¨ê¿\n\u0018,ÝáÜ{¼95oºþÜu3²\t]ïn¤Ji\u0000\u0016 \u0014X\u0004àk!Á\bOÂ)ª+ø;\u001fôhµoÛ+NQ\u0007\rç\u0019%`SBë3ÊÕ_Y\u001d8âÑG\u0011âÞÜê|²2v\u001fI!\u000bÇ¥(G¯ÀÙVðcàzü¿qûþ\u0001\u0000\u0000ÿÿ\u0003\u0000ÿ\u001byÇÅ\u0000\u0000\u0000"

**Comment by napalm272** [comment]
That's a gzipped response. You are likely not setting the version to `v3` (default is v2)

**Comment by youssseeef** [comment]
@ohabash You're likely using Ngrok to test the API. You can see the responses in Ngrok's console. (That was my case at least)

**Comment by philspitler** [comment]
2 things that really helped me out @ohabash....

1. For the instance of `new BigCommerce`, make sure you're using the one that corresponds to the BigCommerce documentation.  So like for /v2/stores, set it to `v2`.

2. Make sure you only use the characters after the '/' (slash) when passing the store hash to make sure it forms the URL correctly.

I hope this helps you, and anyone else that may be having issues.

**Comment by ohabash** [comment]
the solution for me was to switch my version of `node-bigcommerce` to `3.0.0`

**Comment by meesrutten** [comment]
My errors are "gibberish" aswell.

This code returns the error message which I added as an image.
```javascript
const BigCommerce = require('node-bigcommerce');
const bigCommerce = new BigCommerce({
    logLevel: 'info',
    clientId: `${ENV.CLIENT_ID}`,
    secret: `${ENV.CLIENT_SECRET}`,
    storeHash: `${ENV.CLIENT_STOREHASH}`,
    accessToken: `${ENV.CLIENT_ACCESSTOKEN}`,
    responseType: 'json',
    callback: `/auth`,
    apiVersion: 'v3' // Default is v2
});

bigCommerce.post(`/checkouts/${checkoutId}/orders`)
    .then(orderId => {
        console.log(orderId);
        // req.session.orderId = orderId
        resolve(orderId)
    })
    .catch(err => reject(err))
```
![image](https://user-images.githubusercontent.com/10405556/58470601-52e3db80-8142-11e9-97a5-6f339d4e48c3.png)

Is there something I can do about this?

**Comment by youssseeef** [comment]
@meesrutten Go to: http://127.0.0.1:4040/inspect/http and inspect the requests (if you're using ngrok, that's what helped me debug the responses)

**Comment by meesrutten** [comment]
I'm not using Ngrok, just Nodemon...

**Comment by youssseeef** [comment]
@meesrutten Yeah, I believe you're right. I think my case was a bit different. This one is probably due to this way content-encoding is handled inside the library itself.  Someone mentioned that using version 3.0.0 works for them.

**Comment by meesrutten** [comment]
Hmm, problem is still not resolved

**Comment by youssseeef** [comment]
@meesrutten This just came up to my mind but check on your app settings if you have the right scope. It's in #3 technical details when you choose edit app. I hope that's what's going on for you.

**Comment by philspitler** [comment]
@youssseeef, I think you may have found the issue he was having, but not that the error response was gibberish.  I opened https://github.com/getconversio/node-bigcommerce/pull/71 to address this, as well as any future issue regarding BigCommerce request headers.

**Comment by richardkeller411** [comment]
I have same gibberish problem...  In Postman the Error is correctly rendered.  I'm sucessfully firing off on the same path so it is not a config or a "v3" setting.  I'm purposefully firing an error to see the result.   The status codes are correct.. the Gibberish is present in the Error Message.

**Comment by richardkeller411** [comment]
I believe that the error handling may not handle decompression...


          if (res.statusCode >= 400 && res.statusCode <= 600) {
            const error = new Error(`Request returned error code: ${res.statusCode} and body: ${body}`);
            error.code = res.statusCode;
            error.responseBody = body;  <==== ERROR NOT DECOMPRESSED??

            return reject(error);
          }

          // Use GZIP decompression if required
          if (shouldUnzip) {
            const unzip = contentEncoding === 'deflate' ? zlib.deflate : zlib.gunzip;
            return unzip(Buffer.from(body, encoding), (err, data) => {
              if (err) {
                return reject(err);
              }
              return parseResponse(res, data.toString('utf8'), resolve, reject);
            });
          }

          return parseResponse(res, body, resolve, reject);
        });
      });

**Comment by meesrutten** [comment]
Version 4.0.1 of this library still returns gibberish:

![image](https://user-images.githubusercontent.com/10405556/77851091-320f6b00-71d7-11ea-935a-7ef238029a82.png)
![image](https://user-images.githubusercontent.com/10405556/77851108-61be7300-71d7-11ea-90b4-493bd4b40b4d.png)
