### ISSUE TITLE
401 Unauthorized - "X-Auth-Client and X-Auth-Token headers are required"

### ISSUE THREAD

**Issue by ryanfreddy** [getconversio/node-bigcommerce#75]
Hi,

Following the docs, we have put together the following snippet which fails with a 401 and the error message of "X-Auth-Client and X-Auth-Token headers are required":

```es6
import BigCommerce from 'node-bigcommerce'
...

const bigCommerce = new BigCommerce({
  clientId: 'xyz',
  accessToken: 'abc',
  storeHash: 'some_shop',
  responseType: 'json',
  apiVersion: 'v3'
})

bigCommerce.get('/catalog/products')
  .then(data => {
    console.log('data')
  })
```

However, using Postman with the same properties does return the data that is expected.

We are testing the JavaScript in a `localhost` application using Chrome dev tools.

Any ideas as to what may be causing the issue? I believe it may be a CORS issue but I am not certain.

**Comment by bndrgroup** [comment]
+1 @ryanfreddy did you ever get around this?

**Comment by ryanfreddy** [comment]
Hi @bndrgroup, we ended up figuring out that Big Commerce does not allow any CORS requests so we sent the requests using our server and pulled the information to our front end.
