### ISSUE TITLE
Tested PR #80

### ISSUE THREAD

**Issue by meesrutten** [getconversio/node-bigcommerce#81]
I tested PR #80 and this fixes the gibberish when receiving errors.
Is it possible to merge this?

**Comment by willcodeforfood** [comment]
+1 I have the same issue described in #66 
Can we please get this merged and pushed up to NPM?

**Comment by mconatser** [comment]
+1 This is very necessary for handling error cases.

**Comment by stefanosala** [comment]
Merged, sorry for the delay. I'll publish a new version in a second.
